import * as React from "react"
import { withPrefix } from "gatsby"
import { useApplicationContext } from "../../provider"
import { navigate } from "gatsby"
import { Helmet } from "react-helmet"

import Footer from "../components/footer";
import Header from "../components/header";


export default function Home() {
  const [state, setState] = React.useState({
    detailedDescription: "",
    detailedDescription2: ""
  })

  const onChange = (e) => {
    setState({ ...state, [e.target.name]: e.target.value })
  }

  const { applicationState, setApplicationState } = useApplicationContext()
  const onGenerateClick = (e) => {
    e.preventDefault()
    console.log("i have been clicked", state)
    setApplicationState({ ...applicationState, detailedDescription: state.detailedDescription })
    navigate('/choose-art')
  }

  const onGenerateClick2 = (e) => {
    e.preventDefault()
    console.log("i have been clicked", state)
    setApplicationState({ ...applicationState, detailedDescription: state.detailedDescription2 })
    navigate('/choose-art')
  }
  return (
    <>

      <div>
      <Helmet>
            <script src={withPrefix("assets/js/jquery.min.js")} type="text/javascript" />
            {/* <script src={withPrefix("assets/js/jquery.redirect.js")} type="text/javascript" /> */}
            <script src={withPrefix("assets/js/popper.min.js")} type="text/javascript" />
            <script src={withPrefix("assets/js/bootstrap.min.js")} type="text/javascript" />
            <script src={withPrefix("assets/js/custom.js")} type="text/javascript" />
            <script src={withPrefix("assets/js/python.js")} type="text/javascript" />

            <link href={withPrefix("assets/css/bootstrap.min.css")} rel="stylesheet"/>
            <link href={withPrefix("assets/css/brands.min.css")} rel="stylesheet"/>
            <link href={withPrefix("assets/css/light.min.css")} rel="stylesheet"/>
            <link href={withPrefix("assets/css/regular.min.css")} rel="stylesheet"/>
            <link href={withPrefix("assets/css/solid.min.css")} rel="stylesheet"/>
            <link href={withPrefix("assets/css/duotone.min.css")} rel="stylesheet"/>
            <link href={withPrefix("assets/css/fontawesome.min.css")} rel="stylesheet"/>
            <link href={withPrefix("assets/css/custom-styles.css")} rel="stylesheet"/>
        </Helmet>
        <div className="container-main" id="page">
          {/* Header */}
          <Header></Header>
          {/* Content - Main */}
          <main className="content-main">
            <div className="split-cont">
              <div className="container">
                <h2>Create art</h2>
                <div className="feature-links">
                  <div className="aside ">
                    <ul>
                      <li className="active"><a href="#"><p>Default</p></a></li>
                      <li><a href="#">Advanced</a></li>
                    </ul>
                    <div className="sml-txt">.81 credits /image</div>
                  </div>
                </div>
                <div className="row">
                  <div className="col-lg-6">
                    <div className="box">
                      <div className="box-inn">
                        <form>
                          <label>Enter a detailed description:</label>
                          <span style={{ color: 'red', fontSize: 13 }} id="error_create_art" />
                          <textarea name="detailedDescription" id="commentsart2" cols={5} rows={5} placeholder="A digital painting of a puppy french poodle in space surrounded by 3d marshmallow unicorns and stars..." defaultValue="" onChange={onChange} />
                        </form>
                      </div>
                      <p>Images generated by stable difussiion. Learn more.</p>
                      <div className="btn-out"><button name="btnart2" id="btnart2" className="btn" form="get-detailed-description" onClick={onGenerateClick}>GENERATE ART</button></div>

                    </div>
                  </div>
                  <div className="col-lg-6">
                    <div className="feature-list">
                      <div className="heading-top">
                        <div className="aside">
                          <h3>One click merchification &amp; e-Commerce</h3>
                          <p>Begin selling in minutes:</p>
                        </div>
                      </div>
                      <div className="article-wrap">
                        <div className="article-list">
                          <div className="article-out">
                            <div className="article">
                              <div className="box">
                                <div className="figure"><img src={withPrefix("assets/img/photo-1.png")} alt="photo-1" /></div>
                                <h3>1. Generate Art</h3>
                              </div>
                            </div>
                            <div className="article">
                              <div className="box">
                                <div className="figure"><img src={withPrefix("assets/img/photo-2.png")} alt="photo-2" /></div>
                                <h3>2. Make Merchandise</h3>
                              </div>
                            </div>
                            <div className="article">
                              <div className="box">
                                <div className="figure"><img src={withPrefix("assets/img/photo-3.png")} alt="photo-1" /></div>
                                <h3>3. Sell Merch Online</h3>
                              </div>
                            </div>
                            <div className="arrows">
                              <a href="#" className="arrow-right purple"><em className="fal fa-arrow-right" /></a>
                              <a href="#" className="arrow-right"><em className="fal fa-arrow-right" /></a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="split-cont2">
              <div className="container">
                <div className="row">
                  <div className="col-md-6">
                    <div className="figure" id="imageDiffusion">
                      <img id="testimg" src={withPrefix("assets/img/photo-4.png")} alt="photo-4" />
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="feature-links">
                      <h3>Popular categories</h3>
                      <div className="aside-wrap">
                        <div className="aside">
                          <ul>
                            <li className="active"><a href="#">Doggies</a></li>
                            <li><a href="#">Space</a></li>
                            <li><a href="#">Cars</a></li>
                            <li><a href="#">Bubbles</a></li>
                            <li><a href="#">Diamonds</a></li>
                            <li><a href="#">Superhero’s</a></li>
                            <li><a href="#">Category</a></li>
                            <li><a href="#">Fashion</a></li>
                            <li><a href="#">Funny</a></li>
                            <li><a href="#">Games</a></li>
                            <li><a href="#">Category</a></li>
                            <li><a href="#">Category</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="introducing-cont">
              <div className="container">
                <div className="row">
                  <div className="col-md-6">
                    <div className="heading-txt">
                      <div className="sub-title">Introducing</div>
                      <div className="sub-head">Remixer</div>
                      <h2>Edit existing<br /> images</h2>
                      <p>Over 5,000,000 amazing images available through Lexica art.</p>
                      <div className="btn-out"><a href="#" className="btn">sign up</a></div>
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="figure"><img src={withPrefix("assets/img/introducing-group.png")} alt="introducing-group" /></div>
                  </div>
                </div>
              </div>
            </div>
            <div className="featured-images">
              <div className="container">
                <div className="heading-txt">
                  <div className="sub-title">Featured images</div>
                  <h2>Click to Remix</h2>
                  <p>Start creating</p>
                </div>
                <div className="row">
                  <div className="col-lg-4 col-sm-6">
                    <div className="box">
                      <div className="figure"><img src={withPrefix("assets/img/featured-image-1.png")} alt="featured-image-1" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                      <h3>3D</h3>
                    </div>
                  </div>
                  <div className="col-lg-4 col-sm-6">
                    <div className="box">
                      <div className="figure"><img src={withPrefix("assets/img/featured-image-2.png")} alt="featured-image-2" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                      <h3>Abstract</h3>
                    </div>
                  </div>
                  <div className="col-lg-4 col-sm-6">
                    <div className="box">
                      <div className="figure"><img src={withPrefix("assets/img/featured-image-3.png")} alt="featured-image-3" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                      <h3>Architecture</h3>
                    </div>
                  </div>
                  <div className="col-lg-4 col-sm-6">
                    <div className="box">
                      <div className="figure"><img src={withPrefix("assets/img/featured-image-4.png")} alt="featured-image-4" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                      <h3>Nature</h3>
                    </div>
                  </div>
                  <div className="col-lg-4 col-sm-6">
                    <div className="box">
                      <div className="figure"><img src={withPrefix("assets/img/featured-image-5.png")} alt="featured-image-5" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                      <h3>Art &amp; Deco</h3>
                    </div>
                  </div>
                  <div className="col-lg-4 col-sm-6">
                    <div className="box">
                      <div className="figure"><img src={withPrefix("assets/img/featured-image-6.png")} alt="featured-image-6" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                      <h3>Textures</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="generate-art-form">
              <div className="container">
                <div className="box">
                  <form method="get" action="#">
                    <label>What do you want to see?</label>
                    <textarea name="detailedDescription2" id="commentsart" cols={5} rows={5} placeholder="A digital painting of a puppy french poodle in space surrounded by 3d marshmallow unicorns and stars..." defaultValue={""} onChange={onChange} />
                  </form>
                  <p>Images generated by stable difussiion. Learn more.</p>
                </div>
                <div className="btn-out"><button name="btnart2" id="btnart2" className="btn" form="get-detailed-description" onClick={onGenerateClick2}>GENERATE ART</button></div>

              </div>
            </div>
          </main>
          {/* Footer */}
          <Footer></Footer>
        </div>
      </div>
    </>
  )
}